import { } from 'react'

import { Table } from '@arco-design/web-react'

const tableData = [
  {
    id: 16162,
    pid: 2876,
    summary: '车辆费用-过桥过路费-粤BD27Q6-宿迁出差',
    classid: 6,
    acccode: '6601.007.003',
    accname: '过路过桥费',
    accfullname: '销售费用_车辆费用_过路过桥费',
    borrow: 123,
    loan: 0,
    edate: '',
    isbj: 0,
    sort: 1,
    authtype: 0,
    autobuild: 1,
    assistitems: {
      id: 9194,
      pid: 2876,
      eid: 16162,
      bdate: '2025-12-18T00:00:00+08:00',
      money: 123,
      summary: '车辆费用-过桥过路费-粤BD27Q6-宿迁出差',
      items: [
        {
          pid: 2876,
          eid: 16162,
          aid: 9194,
          typeid: 6,
          typename: '成本中心',
          limitgroup: '1',
          sourcetype: 0,
          itemid: 94,
          itemcode: '6002',
          itemname: '销售部',
          itemfullname: '',
        },
      ],
    },
  },
  {
    id: 16163,
    pid: 2876,
    summary: '车辆费用-过桥过路费-粤BD27Q6-接人',
    classid: 6,
    acccode: '6601.007.003',
    accname: '过路过桥费',
    accfullname: '销售费用_车辆费用_过路过桥费',
    borrow: 20,
    loan: 0,
    edate: '',
    isbj: 0,
    sort: 2,
    authtype: 0,
    autobuild: 1,
    assistitems: {
      id: 9195,
      pid: 2876,
      eid: 16163,
      bdate: '2026-01-26T00:00:00+08:00',
      money: 20,
      summary: '车辆费用-过桥过路费-粤BD27Q6-接人',
      items: [
        {
          pid: 2876,
          eid: 16163,
          aid: 9195,
          typeid: 6,
          typename: '成本中心',
          limitgroup: '1',
          sourcetype: 0,
          itemid: 94,
          itemcode: '6002',
          itemname: '销售部',
          itemfullname: '',
        },
      ],
    },
  },
  {
    id: 16164,
    pid: 2876,
    summary: '车辆费用-维修费-粤BD27Q6-维修费',
    classid: 6,
    acccode: '6601.007.004',
    accname: '维修费',
    accfullname: '销售费用_车辆费用_维修费',
    borrow: 5,
    loan: 0,
    edate: '',
    isbj: 0,
    sort: 3,
    authtype: 0,
    autobuild: 1,
    assistitems: {
      id: 9196,
      pid: 2876,
      eid: 16164,
      bdate: '2025-12-11T00:00:00+08:00',
      money: 5,
      summary: '车辆费用-维修费-粤BD27Q6-维修费',
      items: [
        {
          pid: 2876,
          eid: 16164,
          aid: 9196,
          typeid: 6,
          typename: '成本中心',
          limitgroup: '1',
          sourcetype: 0,
          itemid: 94,
          itemcode: '6002',
          itemname: '销售部',
          itemfullname: '',
        },
      ],
    },
  },
  {
    id: 16165,
    pid: 2876,
    summary: '车辆费用-其他-粤BD27Q6-12月份洗车费',
    classid: 6,
    acccode: '6601.007.999',
    accname: '其他',
    accfullname: '销售费用_车辆费用_其他',
    borrow: 75,
    loan: 0,
    edate: '',
    isbj: 0,
    sort: 4,
    authtype: 0,
    autobuild: 1,
    assistitems: {
      id: 9197,
      pid: 2876,
      eid: 16165,
      bdate: '2025-12-08T00:00:00+08:00',
      money: 75,
      summary: '车辆费用-其他-粤BD27Q6-12月份洗车费',
      items: [
        {
          pid: 2876,
          eid: 16165,
          aid: 9197,
          typeid: 6,
          typename: '成本中心',
          limitgroup: '1',
          sourcetype: 0,
          itemid: 94,
          itemcode: '6002',
          itemname: '销售部',
          itemfullname: '',
        },
      ],
    },
  },
  {
    id: 16166,
    pid: 2876,
    summary: '车辆费用-其他-苏A3AQ08-12月份洗车费',
    classid: 6,
    acccode: '6601.007.999',
    accname: '其他',
    accfullname: '销售费用_车辆费用_其他',
    borrow: 25,
    loan: 0,
    edate: '',
    isbj: 0,
    sort: 5,
    authtype: 0,
    autobuild: 1,
    assistitems: {
      id: 9198,
      pid: 2876,
      eid: 16166,
      bdate: '2025-12-08T00:00:00+08:00',
      money: 25,
      summary: '车辆费用-其他-苏A3AQ08-12月份洗车费',
      items: [
        {
          pid: 2876,
          eid: 16166,
          aid: 9198,
          typeid: 6,
          typename: '成本中心',
          limitgroup: '1',
          sourcetype: 0,
          itemid: 94,
          itemcode: '6002',
          itemname: '销售部',
          itemfullname: '',
        },
      ],
    },
  },
  {
    id: 16167,
    pid: 2876,
    summary: '车辆费用-加油费-粤BD27Q6-12月份公司日常加油费',
    classid: 6,
    acccode: '6601.007.002',
    accname: '加油费',
    accfullname: '销售费用_车辆费用_加油费',
    borrow: 1631.61,
    loan: 0,
    edate: '',
    isbj: 0,
    sort: 6,
    authtype: 0,
    autobuild: 1,
    assistitems: {
      id: 9199,
      pid: 2876,
      eid: 16167,
      bdate: '2025-12-19T00:00:00+08:00',
      money: 1631.61,
      summary: '车辆费用-加油费-粤BD27Q6-12月份公司日常加油费',
      items: [
        {
          pid: 2876,
          eid: 16167,
          aid: 9199,
          typeid: 6,
          typename: '成本中心',
          limitgroup: '1',
          sourcetype: 0,
          itemid: 94,
          itemcode: '6002',
          itemname: '销售部',
          itemfullname: '',
        },
      ],
    },
  },
  {
    id: 16168,
    pid: 2876,
    summary: '车辆费用-费用报销-车辆费用',
    classid: 1,
    acccode: '1002.001',
    accname: '人民币',
    accfullname: '银行存款_人民币',
    borrow: 0,
    loan: 1879.61,
    edate: '',
    isbj: 0,
    sort: 7,
    authtype: 0,
    autobuild: 1,
    assistitems: {
      id: 9200,
      pid: 2876,
      eid: 16168,
      bdate: '2026-01-23T00:00:00+08:00',
      money: 1879.61,
      summary: '车辆费用-费用报销-车辆费用',
      items: [
        {
          pid: 2876,
          eid: 16168,
          aid: 9200,
          typeid: 4,
          typename: '银行账户',
          limitgroup: '1',
          sourcetype: 0,
          itemid: 1,
          itemcode: '1001',
          itemname: '招商银行股份有限公司南京城西支行',
          itemfullname: '',
        },
      ],
    },
  },
]

const Demo1 = () => {

  const columns = [
    {
      title: '序号',
      dataIndex: 'order',
      width: 75,
      align: 'center',
    },
    {
      title: '摘要',
      dataIndex: 'summary',
    },
    {
      title: '科目',
      dataIndex: 'accfullname',
      width: 360,
    },
    {
      title: '借方',
      dataIndex: 'borrow',
      align: 'center',
      children: [
        {
          title: '亿',
          dataIndex: 'borrow_10',
          className: 'row-money border-l! border-neutral-200!',
          width: 20,
        },
        {
          title: '千',
          dataIndex: 'borrow_9',
          className: 'row-money',
          width: 20,
        },
        {
          title: '百',
          dataIndex: 'borrow_8',
          className: 'row-money',
          width: 20,
        },
        {
          title: '十',
          dataIndex: 'borrow_7',
          className: 'row-money row-blue',
          width: 20,
        },
        {
          title: '万',
          dataIndex: 'borrow_6',
          className: 'row-money',
          width: 20,
        },
        {
          title: '千',
          dataIndex: 'borrow_5',
          className: 'row-money',
          width: 20,
        },
        {
          title: '百',
          dataIndex: 'borrow_4',
          className: 'row-money row-blue',
          width: 20,
        },
        {
          title: '十',
          dataIndex: 'borrow_3',
          className: 'row-money',
          width: 20,
        },
        {
          title: '元',
          dataIndex: 'borrow_2',
          className: 'row-money',
          width: 20,
        },
        {
          title: '角',
          dataIndex: 'borrow_1',
          className: 'row-money row-red',
          width: 20,
        },
        {
          title: '分',
          dataIndex: 'borrow_0',
          className: 'row-money',
          width: 20,
        },
      ],
    },
    {
      title: '贷方',
      dataIndex: 'loan',
      align: 'center',
      children: [
        {
          title: '亿',
          dataIndex: 'loan_10',
          className: 'row-money',
          width: 20,
        },
        {
          title: '千',
          dataIndex: 'loan_9',
          className: 'row-money',
          width: 20,
        },
        {
          title: '百',
          dataIndex: 'loan_8',
          className: 'row-money',
          width: 20,
        },
        {
          title: '十',
          dataIndex: 'loan_7',
          className: 'row-money row-blue',
          width: 20,
        },
        {
          title: '万',
          dataIndex: 'loan_6',
          className: 'row-money',
          width: 20,
        },
        {
          title: '千',
          dataIndex: 'loan_5',
          className: 'row-money',
          width: 20,
        },
        {
          title: '百',
          dataIndex: 'loan_4',
          className: 'row-money row-blue',
          width: 20,
        },
        {
          title: '十',
          dataIndex: 'loan_3',
          className: 'row-money',
          width: 20,
        },
        {
          title: '元',
          dataIndex: 'loan_2',
          className: 'row-money',
          width: 20,
        },
        {
          title: '角',
          dataIndex: 'loan_1',
          className: 'row-money row-red',
          width: 20,
        },
        {
          title: '分',
          dataIndex: 'loan_0',
          className: 'row-money',
          width: 20,
        },
      ],
    },
  ]

  return (
    <Table columns={columns} data={tableData} rowKey='id' pagination={false} />
  )
}
export default Demo1
